version: "3.8"

services:
  poller:
    build:
      context: .
      dockerfile: poller.containerfile
    volumes:
      - ..:/workspace:cached
    environment:
      - PYTHONUNBUFFERED=1
      - CORE_API_URL=http://core:7000/process-data  # API call to Core instead of Server
    command: ["python", "-m", "switchmap.poller"]
    networks:
      - switchmap-network
    depends_on:
      - core  # Poller needs Core to be running to send data

  core:
    build:
      context: .
      dockerfile: core.containerfile
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - POLLER_API_URL=http://poller:7000/data # (if Core needs to communicate back to Poller)
    networks:
      - switchmap-network

networks:
  switchmap-network:
    driver: bridge
