{
  "idx_device": 1001,
  "ifindex": 5,
  "ifname": "GigabitEthernet0/1",
  "ifdescr": "Uplink port to Switch-B",
  "ifalias": "Core Link",
  "ifoperstatus": 1,
  "ifadminstatus": 1,
  "iftype": 6,
  "ifspeed": 1000000000,
  "duplex": 2,
  "ethernet": 1,
  "nativevlan": 10,
  "trunk": 1,
  "ts_idle": 60,
  "lldpRemSysName": "Switch-B",
  "lldpRemPortDesc": "GigabitEthernet0/24",
  "lldpRemSysDesc": "Cisco Catalyst 2960-X Series Switch",
  "lldpRemSysCapEnabled": ["Bridge", "Router"],
  "cdpcachedeviceid": "Switch-B.corp.local",
  "cdpcachedeviceport": "Gi0/24",
  "cdpcacheplatform": "cisco WS-C2960X-24PD-L",
  "enabled": true,
  "ts_created": "2025-03-18T04:30:00Z",
  "ts_modified": "2025-03-18T04:31:00Z"
}
